// Binary (WASI command) entry point for the headless agent-status aggregator.
// Zellij calls the wasm `_start` export (generated by register_plugin!'s fn
// main), so the artifact MUST be a binary crate. All aggregation logic lives in
// this crate's lib; this file is only the Zellij glue.

#![deny(unsafe_code)]

#[cfg(target_arch = "wasm32")]
mod plugin {
    use std::collections::{BTreeMap, HashMap, HashSet};

    use zellij_tile::prelude::*;
    use zj_radar_agents::{Agents, Config, TabView};
    use zj_radar_core::{parse, STATUS_PIPE_NAME};

    /// Frame clock when nothing is animating. Still sub-second, because it also
    /// carries the publish that `pipe` deliberately defers — an agent hook must
    /// reach the bar in well under a second — but slow enough that an idle
    /// session is not doing 8 broadcasts every second forever.
    const IDLE_SECS: f64 = 0.5;

    /// Where to mirror live state, or `None` if nothing is writable (in which
    /// case reload-survival is simply off — never a startup failure).
    ///
    /// `/cache` is scoped by plugin URL, so it is stable across reloads within a
    /// session. `/data` is NOT: it resolves per instance (`…/<plugin_id>-<client_id>/`),
    /// so a reload that lands a new plugin id would never find yesterday's file —
    /// which is the entire point of writing one. `/tmp/zj-radar` is the fallback
    /// when `/cache` is absent.
    ///
    /// The filename carries `zellij_pid` because `/cache` is shared across
    /// sessions and pane ids are session-scoped: replaying another session's
    /// panes would show agents that do not exist here.
    fn snapshot_path(zellij_pid: u32) -> Option<std::path::PathBuf> {
        let file = format!("state-{zellij_pid}.v1");
        for root in ["/cache", "/tmp/zj-radar"] {
            let root = std::path::Path::new(root);
            if !root.is_dir() && std::fs::create_dir_all(root).is_err() {
                continue;
            }
            // Prove writability now rather than discovering it on every tick —
            // but probe with a SEPARATE name: writing the real file here would
            // truncate the snapshot we are about to read back.
            let probe = root.join(format!("{file}.probe"));
            if std::fs::write(&probe, b"ok").is_ok() {
                let _ = std::fs::remove_file(&probe);
                return Some(root.join(&file));
            }
        }
        None
    }

    #[derive(Default)]
    pub struct AgentsPlugin {
        config: Config,
        agents: Agents,
        /// Wall-clock seconds since load, accumulated from `Event::Timer`'s own
        /// elapsed value. Kept separate from `frame` so TTLs stay correct no
        /// matter which cadence the timer is running at.
        elapsed: f64,
        /// Spinner frame, advanced once per fast tick.
        frame: usize,
        /// Tabs as of the last `TabUpdate`: names, which is active, and bells.
        tabs: Vec<TabView>,
        /// Which tab each terminal pane lives in, from the last `PaneUpdate`.
        /// This is what turns a per-pane agent status into a per-tab indicator.
        pane_tab: HashMap<u32, usize>,
        /// Plugin pane ids seen in the last `PaneUpdate`. A new id means a new
        /// zjstatus instance (a new tab), which starts with an empty widget and
        /// must be seeded without waiting for the next agent event.
        known_plugin_panes: HashSet<u32>,
        /// The last string handed to zjstatus. zjstatus does not compare values
        /// — it re-renders on every pipe message, and its pipe widgets are
        /// exempt from the widget cache — so deduplicating here is the only
        /// thing standing between an idle session and a continuously
        /// repainting status bar.
        last_published: Option<String>,
        /// State changed and the bar has not been told yet. Set by `pipe` and
        /// drained by the next `Timer`; see `pipe` for why the publish cannot
        /// happen inline.
        dirty: bool,
        /// Where live state is mirrored so it survives a plugin reload, and the
        /// last content written there (to avoid rewriting an unchanged file four
        /// times a second).
        snapshot_path: Option<std::path::PathBuf>,
        last_snapshot: Option<String>,
    }

    impl ZellijPlugin for AgentsPlugin {
        fn load(&mut self, configuration: BTreeMap<String, String>) {
            self.config = Config::from_zellij_config(&configuration);
            set_selectable(false);
            hide_self();
            // `ReadApplicationState` gates PaneUpdate *delivery* (subscribing
            // always succeeds); `MessageAndLaunchOtherPlugins` gates
            // `pipe_message_to_plugin`. Receiving CLI pipes needs no permission,
            // and nothing here runs commands or mutates application state.
            request_permission(&[
                PermissionType::ReadApplicationState,
                PermissionType::MessageAndLaunchOtherPlugins,
            ]);
            // TabUpdate carries tab names, which tab is active, and the bell
            // flags; PaneUpdate says which tab each pane is in. Together they
            // turn per-pane agent status into a per-tab indicator.
            subscribe(&[
                EventType::TabUpdate,
                EventType::PaneUpdate,
                EventType::Timer,
            ]);

            // Reload survival. Zellij can reload this plugin mid-session, and
            // producers only emit on a status CHANGE — so without this, an agent
            // that has been "running" for ten minutes leaves the bar blank until
            // it next changes state. Keyed by `zellij_pid` because pane ids are
            // session-scoped: replaying another session's panes would show
            // agents that aren't there.
            let ids = get_plugin_ids();
            if let Some(path) = snapshot_path(ids.zellij_pid) {
                if let Ok(saved) = std::fs::read_to_string(&path) {
                    self.agents.restore(&saved, 0);
                    self.last_snapshot = Some(self.agents.snapshot());
                    // Publish on the first tick so a reload repaints the bar
                    // immediately rather than waiting for the next agent event.
                    self.dirty = true;
                }
                self.snapshot_path = Some(path);
            }

            set_timeout(IDLE_SECS);
        }

        fn update(&mut self, event: Event) -> bool {
            match event {
                Event::Timer(late) => {
                    // Zellij reports how late the callback fired, not which
                    // duration it belonged to, so accumulate its elapsed value
                    // rather than counting ticks: TTLs then stay correct across
                    // a cadence change.
                    self.elapsed += late.max(0.0);
                    let animating = self.animating();
                    if animating {
                        self.frame = self.frame.wrapping_add(1);
                    }
                    let expired = self.agents.expire(self.elapsed as u64, &self.config);
                    if self.dirty || expired || animating {
                        self.dirty = false;
                        self.publish();
                    }
                    set_timeout(if animating {
                        self.config.animate_secs()
                    } else {
                        IDLE_SECS
                    });
                }
                Event::TabUpdate(tabs) => self.tabs_changed(tabs),
                Event::PaneUpdate(manifest) => self.panes_changed(manifest),
                _ => {}
            }
            // Never renders: a background plugin is sized 0x0, so Zellij skips
            // `render` regardless. Returning false keeps that explicit.
            false
        }

        /// Fold one agent status in and return IMMEDIATELY. This handler must do
        /// no host I/O at all — in particular it must NOT publish.
        ///
        /// `zellij pipe` blocks its client until every recipient plugin has
        /// returned from `pipe` (`zellij-server/src/plugins/pipes.rs:124`
        /// releases the CLI pipe only once `currently_being_processed_by` is
        /// empty). Calling `pipe_message_to_plugin` from inside this handler
        /// fans a new message out to every plugin instance while the CLI pipe
        /// that triggered it is still outstanding; under repeated hook traffic
        /// that wedges the server's wasm thread permanently — every subsequent
        /// `zellij pipe` AND `zellij action` blocks forever, session-wide.
        /// (Observed: fine for a handful of sends, dead after a burst of ten.)
        ///
        /// So: record, mark dirty, return. The next `Timer` publishes, ≤250 ms
        /// later, safely outside the pipe's critical section. This is also why
        /// `zellij-resource-status` — the working precedent — only ever
        /// publishes from `update`.
        fn pipe(&mut self, message: PipeMessage) -> bool {
            if message.name != STATUS_PIPE_NAME {
                return false;
            }
            if let Some(raw) = message.payload.as_deref() {
                if let Some(payload) = parse(raw) {
                    if self.agents.apply(&payload, self.elapsed as u64) {
                        self.dirty = true;
                    }
                }
            }
            // `false` also takes Zellij's fast path, which releases the blocked
            // CLI pipe without waiting on a render round-trip.
            false
        }
    }

    impl AgentsPlugin {
        /// Whether the bar must keep repainting: a working spinner to advance, or
        /// a bell mid-flash. Everything else is a settled picture that only needs
        /// redrawing when it changes.
        fn animating(&self) -> bool {
            self.config.animate()
                && (self.agents.any_running() || self.tabs.iter().any(|t| t.flashing_bell))
        }

        fn tabs_changed(&mut self, tabs: Vec<TabInfo>) {
            let next: Vec<TabView> = tabs
                .into_iter()
                .map(|t| TabView {
                    position: t.position,
                    name: t.name,
                    active: t.active,
                    bell: t.has_bell_notification,
                    flashing_bell: t.is_flashing_bell,
                    sync: t.is_sync_panes_active,
                    fullscreen: t.is_fullscreen_active,
                    columns: t.viewport_columns,
                })
                .collect();
            if next != self.tabs {
                self.tabs = next;
                self.dirty = true;
            }
        }

        fn panes_changed(&mut self, manifest: PaneManifest) {
            let mut live_terminals = HashSet::new();
            let mut plugin_panes = HashSet::new();
            let mut pane_tab = HashMap::new();
            for (tab_position, panes) in &manifest.panes {
                for pane in panes {
                    if pane.is_plugin {
                        plugin_panes.insert(pane.id);
                    } else {
                        live_terminals.insert(pane.id);
                        pane_tab.insert(pane.id, *tab_position);
                    }
                }
            }
            if pane_tab != self.pane_tab {
                // A pane moved tabs, or one appeared/vanished: the strip changes
                // even when no agent status did.
                self.pane_tab = pane_tab;
                self.dirty = true;
            }

            if self.agents.retain_panes(&live_terminals) {
                self.dirty = true;
            }
            if !plugin_panes.is_subset(&self.known_plugin_panes) {
                // A zjstatus instance we have never published to (a new tab).
                // Drop the dedup cache so the next publish actually goes out and
                // seeds it instead of being suppressed as "unchanged".
                self.last_published = None;
                self.dirty = true;
            }
            self.known_plugin_panes = plugin_panes;
        }

        /// The ONE place that talks to other plugins. Reached only from the
        /// `Timer` arm, never from `pipe` — see `pipe` for why that matters.
        fn publish(&mut self) {
            self.persist();
            let glyphs = self.config.glyphs();
            // One widget, one directive. The content must stay newline-free:
            // zjstatus reads '\n' as a directive separator.
            let payload = self.config.pipe_payload(
                &self
                    .agents
                    .render_tabs(
                        &self.tabs,
                        &self.pane_tab,
                        glyphs,
                        self.frame,
                        // The bar spans the whole width; any tab reports it.
                        self.tabs.first().map_or(0, |t| t.columns),
                    ),
            );
            if self.last_published.as_deref() == Some(payload.as_str()) {
                return;
            }
            // No `with_plugin_url` and no destination id: that combination is
            // what makes Zellij broadcast to every live plugin instance, which
            // is the only way to reach every zjstatus at once. Targeting by URL
            // would miss instances configured differently.
            pipe_message_to_plugin(
                MessageToPlugin::new("zj-radar-agents").with_payload(payload.clone()),
            );
            self.last_published = Some(payload);
        }

        /// Mirror live state to disk for the next load. Skipped when unchanged,
        /// so an idle session does no I/O even though the timer runs at 4 Hz.
        /// A write failure is deliberately ignored: losing reload-survival is a
        /// far smaller problem than a plugin that stops reporting agents.
        fn persist(&mut self) {
            let Some(path) = self.snapshot_path.as_ref() else {
                return;
            };
            let snapshot = self.agents.snapshot();
            if self.last_snapshot.as_deref() == Some(snapshot.as_str()) {
                return;
            }
            if std::fs::write(path, &snapshot).is_ok() {
                self.last_snapshot = Some(snapshot);
            }
        }
    }
}

// `register_plugin!` expands to code calling the trait's methods, so the trait
// must be in scope at the crate root, not just inside `mod plugin`.
#[cfg(target_arch = "wasm32")]
use zellij_tile::prelude::*;

#[cfg(target_arch = "wasm32")]
zellij_tile::register_plugin!(plugin::AgentsPlugin);

#[cfg(not(target_arch = "wasm32"))]
fn main() {}
