// Binary (WASI command) entry point for the headless agent-status aggregator.
// Zellij calls the wasm `_start` export (generated by register_plugin!'s fn
// main), so the artifact MUST be a binary crate. All aggregation logic lives in
// this crate's lib; this file is only the Zellij glue.

#![deny(unsafe_code)]

#[cfg(target_arch = "wasm32")]
mod plugin {
    use std::collections::{BTreeMap, HashSet};

    use zellij_tile::prelude::*;
    use zj_radar_agents::{Agents, Config};
    use zj_radar_core::{parse, STATUS_PIPE_NAME};

    /// Frequency of the one timer this plugin keeps armed. There is no animation
    /// to drive — the status glyphs are static — so this exists only to (a) age
    /// entries out and (b) carry the publish that `pipe` deliberately defers,
    /// which is why it is sub-second: an agent hook must reach the bar in well
    /// under a second.
    const TICK_SECS: f64 = 0.25;

    /// Ticks per wall-clock second, for converting the tick counter into the
    /// seconds that `Agents::expire` reasons about.
    const TICKS_PER_SEC: u64 = 4;

    #[derive(Default)]
    pub struct AgentsPlugin {
        config: Config,
        agents: Agents,
        tick: u64,
        /// Plugin pane ids seen in the last `PaneUpdate`. A new id means a new
        /// zjstatus instance (a new tab), which starts with an empty widget and
        /// must be seeded without waiting for the next agent event.
        known_plugin_panes: HashSet<u32>,
        /// The last string handed to zjstatus. zjstatus does not compare values
        /// — it re-renders on every pipe message, and its pipe widgets are
        /// exempt from the widget cache — so deduplicating here is the only
        /// thing standing between an idle session and a continuously
        /// repainting status bar.
        last_published: Option<String>,
        /// State changed and the bar has not been told yet. Set by `pipe` and
        /// drained by the next `Timer`; see `pipe` for why the publish cannot
        /// happen inline.
        dirty: bool,
    }

    impl ZellijPlugin for AgentsPlugin {
        fn load(&mut self, configuration: BTreeMap<String, String>) {
            self.config = Config::from_zellij_config(&configuration);
            set_selectable(false);
            hide_self();
            // `ReadApplicationState` gates PaneUpdate *delivery* (subscribing
            // always succeeds); `MessageAndLaunchOtherPlugins` gates
            // `pipe_message_to_plugin`. Receiving CLI pipes needs no permission,
            // and nothing here runs commands or mutates application state.
            request_permission(&[
                PermissionType::ReadApplicationState,
                PermissionType::MessageAndLaunchOtherPlugins,
            ]);
            subscribe(&[EventType::PaneUpdate, EventType::Timer]);
            set_timeout(TICK_SECS);
        }

        fn update(&mut self, event: Event) -> bool {
            match event {
                Event::Timer(_) => {
                    self.tick += 1;
                    let expired = self.agents.expire(self.tick / TICKS_PER_SEC, &self.config);
                    if self.dirty || expired {
                        self.dirty = false;
                        self.publish();
                    }
                    set_timeout(TICK_SECS);
                }
                Event::PaneUpdate(manifest) => self.panes_changed(manifest),
                _ => {}
            }
            // Never renders: a background plugin is sized 0x0, so Zellij skips
            // `render` regardless. Returning false keeps that explicit.
            false
        }

        /// Fold one agent status in and return IMMEDIATELY. This handler must do
        /// no host I/O at all — in particular it must NOT publish.
        ///
        /// `zellij pipe` blocks its client until every recipient plugin has
        /// returned from `pipe` (`zellij-server/src/plugins/pipes.rs:124`
        /// releases the CLI pipe only once `currently_being_processed_by` is
        /// empty). Calling `pipe_message_to_plugin` from inside this handler
        /// fans a new message out to every plugin instance while the CLI pipe
        /// that triggered it is still outstanding; under repeated hook traffic
        /// that wedges the server's wasm thread permanently — every subsequent
        /// `zellij pipe` AND `zellij action` blocks forever, session-wide.
        /// (Observed: fine for a handful of sends, dead after a burst of ten.)
        ///
        /// So: record, mark dirty, return. The next `Timer` publishes, ≤250 ms
        /// later, safely outside the pipe's critical section. This is also why
        /// `zellij-resource-status` — the working precedent — only ever
        /// publishes from `update`.
        fn pipe(&mut self, message: PipeMessage) -> bool {
            if message.name != STATUS_PIPE_NAME {
                return false;
            }
            if let Some(raw) = message.payload.as_deref() {
                if let Some(payload) = parse(raw) {
                    if self.agents.apply(&payload, self.tick / TICKS_PER_SEC) {
                        self.dirty = true;
                    }
                }
            }
            // `false` also takes Zellij's fast path, which releases the blocked
            // CLI pipe without waiting on a render round-trip.
            false
        }
    }

    impl AgentsPlugin {
        fn panes_changed(&mut self, manifest: PaneManifest) {
            let mut live_terminals = HashSet::new();
            let mut plugin_panes = HashSet::new();
            for panes in manifest.panes.values() {
                for pane in panes {
                    if pane.is_plugin {
                        plugin_panes.insert(pane.id);
                    } else {
                        live_terminals.insert(pane.id);
                    }
                }
            }

            if self.agents.retain_panes(&live_terminals) {
                self.dirty = true;
            }
            if !plugin_panes.is_subset(&self.known_plugin_panes) {
                // A zjstatus instance we have never published to (a new tab).
                // Drop the dedup cache so the next publish actually goes out and
                // seeds it instead of being suppressed as "unchanged".
                self.last_published = None;
                self.dirty = true;
            }
            self.known_plugin_panes = plugin_panes;
        }

        /// The ONE place that talks to other plugins. Reached only from the
        /// `Timer` arm, never from `pipe` — see `pipe` for why that matters.
        fn publish(&mut self) {
            let payload = self.config.pipe_payload(&self.agents.render(self.config.glyphs()));
            if self.last_published.as_deref() == Some(payload.as_str()) {
                return;
            }
            // No `with_plugin_url` and no destination id: that combination is
            // what makes Zellij broadcast to every live plugin instance, which
            // is the only way to reach every zjstatus at once. Targeting by URL
            // would miss instances configured differently.
            pipe_message_to_plugin(
                MessageToPlugin::new("zj-radar-agents").with_payload(payload.clone()),
            );
            self.last_published = Some(payload);
        }
    }
}

// `register_plugin!` expands to code calling the trait's methods, so the trait
// must be in scope at the crate root, not just inside `mod plugin`.
#[cfg(target_arch = "wasm32")]
use zellij_tile::prelude::*;

#[cfg(target_arch = "wasm32")]
zellij_tile::register_plugin!(plugin::AgentsPlugin);

#[cfg(not(target_arch = "wasm32"))]
fn main() {}
